# ==============================================================================
# Naming and tagging
# ==============================================================================
variable "project" {
  type        = string
  default     = "poly"
  description = "Project token used in every resource name and in the `project` tag."
}

variable "environment" {
  type        = string
  default     = "dev"
  description = "Environment token used in every resource name and in the `environment` tag. A single environment exists (CLAUDE.md decision #13), and a single deployment target — no slots (decision #11)."

  validation {
    condition     = contains(["dev"], var.environment)
    error_message = "Un seul environnement est prévu sur ce projet : dev (décision #13). Ajouter une valeur ici implique d'arbitrer le coût d'une infra dupliquée."
  }
}

variable "owner" {
  type        = string
  default     = "vincent"
  description = "Value of the `owner` tag on every resource."
}

# ==============================================================================
# Infrastructure
# ==============================================================================
variable "resource_group_location" {
  type        = string
  default     = "francecentral"
  description = "Azure region hosting every resource of the project (CLAUDE.md decision #14). The naming token (frc, weu...) is derived from this value by `local.region_short_by_location` in main.tf — there is deliberately no second variable to keep in sync."

  # La liste reste plus large que la décision #14 (`francecentral`), à la
  # différence de `environment` verrouillé sur une seule valeur : ce qu'elle
  # garantit n'est pas le respect de la décision mais l'existence d'un jeton de
  # nommage. Changer de région reste possible sans toucher à la validation,
  # déplacer l'infra dans un second environnement non.
  validation {
    condition     = contains(["francecentral", "westeurope", "northeurope"], var.resource_group_location)
    error_message = "Région non reconnue. Ce champ pilote aussi le jeton de région des noms de ressources : ajouter une région ici impose d'ajouter son jeton court dans `local.region_short_by_location` (main.tf), sinon le plan échoue sur un index manquant."
  }
}

variable "service_plan_sku" {
  type        = string
  default     = "B1"
  description = "SKU of the shared App Service plan hosting the vote front end and the worker. B1 by default (CLAUDE.md decision #11): the project demonstrates a pipeline, not a production topology. Deployment slots need Standard or above — moving up is a one-line change here, but it also brings back `azurerm_linux_web_app_slot` and the swap stage, both removed."

  validation {
    # Le plancher est le tier dédié : Free et Shared partagent leur machine,
    # n'offrent ni intégration VNET ni conteneurs Linux, et l'app ne
    # démarrerait pas. L'erreur n'apparaîtrait qu'à l'apply.
    condition     = can(regex("^(B[1-3]|S[1-3]|P[1-3]v2|P[0-3]v3)$", var.service_plan_sku))
    error_message = "SKU non supporté. Il faut un tier dédié : Basic (B1-B3), Standard (S1-S3) ou Premium (P1v2-P3v2, P0v3-P3v3). Free et Shared n'offrent ni intégration VNET ni conteneurs Linux."
  }
}

# ==============================================================================
# PostgreSQL
# ==============================================================================
variable "postgresql_administrator_login" {
  type        = string
  default     = "psqladmin"
  description = "Administrator login of the PostgreSQL flexible server. The password is not a variable: it is generated by `random_password.psql_admin` so that no credential ever transits through `terraform.tfvars`, hence through Git."

  validation {
    # Azure réserve ces trois identifiants et refuse la création du serveur si
    # l'un d'eux est demandé — l'erreur n'apparaît qu'à l'apply.
    condition     = !contains(["azure_superuser", "azure_pg_admin", "admin"], lower(var.postgresql_administrator_login))
    error_message = "Identifiant réservé par Azure. Utiliser autre chose que `azure_superuser`, `azure_pg_admin` ou `admin`."
  }
}

# ==============================================================================
# Container image
# ==============================================================================
# Les trois web apps tirent désormais leur image de l'ACR du projet — plus de
# registre externe à distinguer par préfixe. Chaque variable ne porte que le
# `repository:tag` ; l'URL du registre est calculée à l'apply
# (`azurerm_container_registry.acr.login_server`) et ne peut donc pas vivre ici.
variable "web_app_worker_docker_image_name" {
  type        = string
  description = "Repository and tag of the worker image in the project ACR, as `repository:tag`. Bootstrap value only: Terraform sets it at creation, then `ignore_changes` hands the tag over to the pipeline, which deploys `$(Build.BuildId)` on every run. Until the first pipeline run this image does not exist yet and the worker will not start."

  validation {
    condition     = can(regex("^.+:[A-Za-z0-9_][A-Za-z0-9._-]*$", var.web_app_worker_docker_image_name)) && !endswith(var.web_app_worker_docker_image_name, ":latest")
    error_message = "L'image doit porter un tag explicite et non vide, autre que `latest` (ex. `polytech/worker:0.1.0`) — sinon la version réellement déployée n'est pas reproductible."
  }
}

variable "web_app_vote_docker_image_name" {
  type        = string
  description = "Repository and tag of the vote image in the project ACR, as `repository:tag`. Bootstrap value only, same `ignore_changes` handoff to the pipeline as the worker. No default: a web app deployed without an image is broken, and an empty default hides that until runtime."

  validation {
    # Le tag est ce qui suit le dernier `:` et ne peut pas contenir de `/` :
    # ça écarte `repo` (pas de tag), `repo:` (tag vide) et `host:5000/repo`
    # (le `:` est celui du port, pas d'un tag). `latest` est refusé à part,
    # puisqu'il est syntaxiquement valide mais non reproductible.
    condition     = can(regex("^.+:[A-Za-z0-9_][A-Za-z0-9._-]*$", var.web_app_vote_docker_image_name)) && !endswith(var.web_app_vote_docker_image_name, ":latest")
    error_message = "L'image doit porter un tag explicite et non vide, autre que `latest` (ex. `polytech/vote:1.0.1`) — sinon la version réellement déployée n'est pas reproductible."
  }
}

variable "web_app_result_docker_image_name" {
  type        = string
  description = "Repository and tag of the result image in the project ACR, as `repository:tag`. Bootstrap value only, same `ignore_changes` handoff to the pipeline as the worker and the vote."

  validation {
    condition     = can(regex("^.+:[A-Za-z0-9_][A-Za-z0-9._-]*$", var.web_app_result_docker_image_name)) && !endswith(var.web_app_result_docker_image_name, ":latest")
    error_message = "L'image doit porter un tag explicite et non vide, autre que `latest` (ex. `polytech/result:1.0.1`) — sinon la version réellement déployée n'est pas reproductible."
  }
}
